/* automatically generated by rust-bindgen 0.71.1 */

unsafe extern "C" {
    pub fn mrbc_main(
        argc: ::std::os::raw::c_int,
        argv: *mut *mut ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
